language: generic

matrix:
  include:
    - script:
        - make test-xcode
      env: JOB=Xcode
      os: osx
      osx_image: xcode8.3
      before_install:
        - rvm list
        - rvm install $(cat .ruby-version)
        - make setup
    - script:
        - make test
        - make lint-cli
      env: JOB=SwiftPM
      os: osx
      osx_image: xcode8.3
      before_install:
        - rvm list
        - rvm install $(cat .ruby-version)
        - make setup
    - script:
        - docker run -it -d -P mockingbird bash -c "make test"
      env: JOB=Linux
      sudo: required
      services: docker
      before_install:
        - make build-docker
        - docker ps -a
